export const FETCH_LECTURE_SCHEDULES_LOADING = 'FETCH_LECTURE_SCHEDULES_LOADING';
export const FETCH_LECTURE_SCHEDULES_SUCCESS = 'FETCH_LECTURE_SCHEDULES_SUCCESS';
export const FETCH_LECTURE_SCHEDULES_FAILURE = 'FETCH_LECTURE_SCHEDULES_FAILURE';